
 //tableNameScript script 
function doWh_pick_master(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=wh_pick_master'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['WHPKNo'] != undefined){	eval('document.'+ formName).elements['WHPKNo'].value = theValue[0];}if(eval('document.'+ formName).elements['DeptID'] != undefined){	eval('document.'+ formName).elements['DeptID'].value = theValue[1];}	}}
function doPl_pmobom_master(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=pl_pmobom_master'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['PLPKNo'] != undefined){	eval('document.'+ formName).elements['PLPKNo'].value = theValue[0];}if(eval('document.'+ formName).elements['PMoItem'] != undefined){	eval('document.'+ formName).elements['PMoItem'].value = theValue[1];}if(eval('document.'+ formName).elements['Name'] != undefined){	eval('document.'+ formName).elements['Name'].value = theValue[2];}	}}
function doSys_menu_master(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=sys_menu_master'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['menug_id'] != undefined){	eval('document.'+ formName).elements['menug_id'].value = theValue[0];}if(eval('document.'+ formName).elements['menug_name'] != undefined){	eval('document.'+ formName).elements['menug_name'].value = theValue[1];}	}}
function doCa_cardinfo(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=ca_cardinfo'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['card_id'] != undefined){	eval('document.'+ formName).elements['card_id'].value = theValue[0];}if(eval('document.'+ formName).elements['dept_id'] != undefined){	eval('document.'+ formName).elements['dept_id'].value = theValue[1];}if(eval('document.'+ formName).elements['dept_name'] != undefined){	eval('document.'+ formName).elements['dept_name'].value = theValue[2];}	}}
function doPu_supplier(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=pu_supplier'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['SupplierID'] != undefined){	eval('document.'+ formName).elements['SupplierID'].value = theValue[0];}if(eval('document.'+ formName).elements['SupplierName'] != undefined){	eval('document.'+ formName).elements['SupplierName'].value = theValue[1];}if(eval('document.'+ formName).elements['Tel'] != undefined){	eval('document.'+ formName).elements['Tel'].value = theValue[2];}	}}
function doSl_shipping_view(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=sl_shipping_view'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['CustomerID'] != undefined){	eval('document.'+ formName).elements['CustomerID'].value = theValue[0];}if(eval('document.'+ formName).elements['CustomerName'] != undefined){	eval('document.'+ formName).elements['CustomerName'].value = theValue[1];}if(eval('document.'+ formName).elements['ShippingID'] != undefined){	eval('document.'+ formName).elements['ShippingID'].value = theValue[2];}if(eval('document.'+ formName).elements['Tel'] != undefined){	eval('document.'+ formName).elements['Tel'].value = theValue[3];}	}}
function doWh_storebin(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=wh_storebin'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['Store'] != undefined){	eval('document.'+ formName).elements['Store'].value = theValue[0];}if(eval('document.'+ formName).elements['Bin'] != undefined){	eval('document.'+ formName).elements['Bin'].value = theValue[1];}if(eval('document.'+ formName).elements['Feature'] != undefined){	eval('document.'+ formName).elements['Feature'].value = theValue[2];}if(eval('document.'+ formName).elements['Description'] != undefined){	eval('document.'+ formName).elements['Description'].value = theValue[3];}	}}
function doBa_item(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=ba_item'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['Item'] != undefined){	eval('document.'+ formName).elements['Item'].value = theValue[0];}if(eval('document.'+ formName).elements['SBST'] != undefined){	eval('document.'+ formName).elements['SBST'].value = theValue[1];}if(eval('document.'+ formName).elements['ItemClass'] != undefined){	eval('document.'+ formName).elements['ItemClass'].value = theValue[2];}if(eval('document.'+ formName).elements['Model'] != undefined){	eval('document.'+ formName).elements['Model'].value = theValue[3];}if(eval('document.'+ formName).elements['Drawing'] != undefined){	eval('document.'+ formName).elements['Drawing'].value = theValue[4];}if(eval('document.'+ formName).elements['Name'] != undefined){	eval('document.'+ formName).elements['Name'].value = theValue[5];}if(eval('document.'+ formName).elements['Specification'] != undefined){	eval('document.'+ formName).elements['Specification'].value = theValue[6];}if(eval('document.'+ formName).elements['material'] != undefined){	eval('document.'+ formName).elements['material'].value = theValue[7];}if(eval('document.'+ formName).elements['MB'] != undefined){	eval('document.'+ formName).elements['MB'].value = theValue[8];}if(eval('document.'+ formName).elements['IfProduct'] != undefined){	eval('document.'+ formName).elements['IfProduct'].value = theValue[9];}if(eval('document.'+ formName).elements['LDeptID'] != undefined){	eval('document.'+ formName).elements['LDeptID'].value = theValue[10];}if(eval('document.'+ formName).elements['NDeptID'] != undefined){	eval('document.'+ formName).elements['NDeptID'].value = theValue[11];}if(eval('document.'+ formName).elements['EDeptID'] != undefined){	eval('document.'+ formName).elements['EDeptID'].value = theValue[12];}	}}
function doSl_salesitem_view(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=sl_salesitem_view'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['SItem'] != undefined){	eval('document.'+ formName).elements['SItem'].value = theValue[0];}if(eval('document.'+ formName).elements['Item'] != undefined){	eval('document.'+ formName).elements['Item'].value = theValue[1];}	}}
function doPl_dept(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=pl_dept'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['DeptID'] != undefined){	eval('document.'+ formName).elements['DeptID'].value = theValue[0];}if(eval('document.'+ formName).elements['DeptName'] != undefined){	eval('document.'+ formName).elements['DeptName'].value = theValue[1];}if(eval('document.'+ formName).elements['DeptFName'] != undefined){	eval('document.'+ formName).elements['DeptFName'].value = theValue[2];}if(eval('document.'+ formName).elements['DeptAddress'] != undefined){	eval('document.'+ formName).elements['DeptAddress'].value = theValue[3];}if(eval('document.'+ formName).elements['DeptFeature'] != undefined){	eval('document.'+ formName).elements['DeptFeature'].value = theValue[4];}if(eval('document.'+ formName).elements['workid'] != undefined){	eval('document.'+ formName).elements['workid'].value = theValue[5];}	}}
function doSys_menuidx_main(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=sys_menuidx_main'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['menug_id'] != undefined){	eval('document.'+ formName).elements['menug_id'].value = theValue[0];}if(eval('document.'+ formName).elements['menug_name'] != undefined){	eval('document.'+ formName).elements['menug_name'].value = theValue[1];}	}}
function doSl_customer(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&recvTablename=&displayName=sl_customer'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['CustomerID'] != undefined){	eval('document.'+ formName).elements['CustomerID'].value = theValue[0];}if(eval('document.'+ formName).elements['CustomerName'] != undefined){	eval('document.'+ formName).elements['CustomerName'].value = theValue[1];}if(eval('document.'+ formName).elements['Country'] != undefined){	eval('document.'+ formName).elements['Country'].value = theValue[2];}	}}
function doBa_routers(formName, element_name, thisObj){  
	var today 		= new Date(); 	var cur_time	= today.getTime(); 	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=零件综合工艺信息&recvTablename=&displayName=ba_routers'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 	if(theValue==null){   	theValue=''; 	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(eval('document.'+ formName).elements['id'] != undefined){	eval('document.'+ formName).elements['id'].value = theValue[0];}if(eval('document.'+ formName).elements['Item'] != undefined){	eval('document.'+ formName).elements['Item'].value = theValue[1];}if(eval('document.'+ formName).elements['part_id'] != undefined){	eval('document.'+ formName).elements['part_id'].value = theValue[2];}if(eval('document.'+ formName).elements['part_name'] != undefined){	eval('document.'+ formName).elements['part_name'].value = theValue[3];}if(eval('document.'+ formName).elements['process_typename'] != undefined){	eval('document.'+ formName).elements['process_typename'].value = theValue[4];}if(eval('document.'+ formName).elements['router_code'] != undefined){	eval('document.'+ formName).elements['router_code'].value = theValue[5];}if(eval('document.'+ formName).elements['router_name'] != undefined){	eval('document.'+ formName).elements['router_name'].value = theValue[6];}if(eval('document.'+ formName).elements['workshop'] != undefined){	eval('document.'+ formName).elements['workshop'].value = theValue[7];}	}}

 //tableNameScript_line script 
function doBa_item_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&popid=45&recvTablename=&displayName=ba_item'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('Item'+element_id) != undefined){		document.getElementById('Item'+element_id).value = theValue[0];}if( document.getElementById('SBST'+element_id) != undefined){		document.getElementById('SBST'+element_id).value = theValue[1];}if( document.getElementById('ItemClass'+element_id) != undefined){		document.getElementById('ItemClass'+element_id).value = theValue[2];}if( document.getElementById('Model'+element_id) != undefined){		document.getElementById('Model'+element_id).value = theValue[3];}if( document.getElementById('Drawing'+element_id) != undefined){		document.getElementById('Drawing'+element_id).value = theValue[4];}if( document.getElementById('Name'+element_id) != undefined){		document.getElementById('Name'+element_id).value = theValue[5];}if( document.getElementById('Specification'+element_id) != undefined){		document.getElementById('Specification'+element_id).value = theValue[6];}if( document.getElementById('material'+element_id) != undefined){		document.getElementById('material'+element_id).value = theValue[7];}if( document.getElementById('MB'+element_id) != undefined){		document.getElementById('MB'+element_id).value = theValue[8];}if( document.getElementById('IfProduct'+element_id) != undefined){		document.getElementById('IfProduct'+element_id).value = theValue[9];}if( document.getElementById('LDeptID'+element_id) != undefined){		document.getElementById('LDeptID'+element_id).value = theValue[10];}if( document.getElementById('NDeptID'+element_id) != undefined){		document.getElementById('NDeptID'+element_id).value = theValue[11];}if( document.getElementById('EDeptID'+element_id) != undefined){		document.getElementById('EDeptID'+element_id).value = theValue[12];}	}}
function doBa_part_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&popid=46&recvTablename=&displayName=ba_part'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('part_id'+element_id) != undefined){		document.getElementById('part_id'+element_id).value = theValue[0];}if( document.getElementById('part_name'+element_id) != undefined){		document.getElementById('part_name'+element_id).value = theValue[1];}if( document.getElementById('part_feature'+element_id) != undefined){		document.getElementById('part_feature'+element_id).value = theValue[2];}	}}
function doBa_tools_linepr_prcss1(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=工具(夹、刃、量具)选择&popid=47&recvTablename=pr_prcss&displayName=ba_tools'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(document.getElementById('jig_name'+ element_id) != undefined){ 		document.getElementById('jig_name'+ element_id).value	= theValue[2]; }if(document.getElementById('tooltype'+ element_id) != undefined){ 		document.getElementById('tooltype'+ element_id).value	= theValue[0]; }if(document.getElementById('jig_id'+ element_id) != undefined){ 		document.getElementById('jig_id'+ element_id).value	= theValue[1]; }	}}
function doBa_device_linepr_prcss1(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=设备与工作中心选择&popid=48&recvTablename=pr_prcss&displayName=ba_device'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(document.getElementById('workshop'+ element_id) != undefined){ 		document.getElementById('workshop'+ element_id).value	= theValue[3]; }if(document.getElementById('wkctcode'+ element_id) != undefined){ 		document.getElementById('wkctcode'+ element_id).value	= theValue[2]; }if(document.getElementById('equipment_id'+ element_id) != undefined){ 		document.getElementById('equipment_id'+ element_id).value	= theValue[0]; }if(document.getElementById('equipment_name'+ element_id) != undefined){ 		document.getElementById('equipment_name'+ element_id).value	= theValue[1]; }	}}
function doBa_tools_linepr_prcss2(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=工具(夹、刃、量具)选择&popid=49&recvTablename=pr_prcss&displayName=ba_tools'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(document.getElementById('edge_name'+ element_id) != undefined){ 		document.getElementById('edge_name'+ element_id).value	= theValue[2]; }if(document.getElementById('tooltype'+ element_id) != undefined){ 		document.getElementById('tooltype'+ element_id).value	= theValue[0]; }if(document.getElementById('edge_id'+ element_id) != undefined){ 		document.getElementById('edge_id'+ element_id).value	= theValue[1]; }	}}
function doBa_tools_linepr_prcss3(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=工具(夹、刃、量具)选择&popid=50&recvTablename=pr_prcss&displayName=ba_tools'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(document.getElementById('calibrater_name'+ element_id) != undefined){ 		document.getElementById('calibrater_name'+ element_id).value	= theValue[2]; }if(document.getElementById('tooltype'+ element_id) != undefined){ 		document.getElementById('tooltype'+ element_id).value	= theValue[0]; }if(document.getElementById('calibrater_id'+ element_id) != undefined){ 		document.getElementById('calibrater_id'+ element_id).value	= theValue[1]; }	}}
function doBa_part_lineba_abom1(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=零件选择&popid=51&recvTablename=ba_abom&displayName=ba_part'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if(document.getElementById('childpart_id'+ element_id) != undefined){ 		document.getElementById('childpart_id'+ element_id).value	= theValue[0]; }if(document.getElementById('childpart_name'+ element_id) != undefined){ 		document.getElementById('childpart_name'+ element_id).value	= theValue[1]; }	}}
function doBa_device_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=设备与工作中心选择&popid=52&recvTablename=&displayName=ba_device'; 
	var style			= 'status:no;help:no;dialogWidth:42;dialogHeight:22;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('id'+element_id) != undefined){		document.getElementById('id'+element_id).value = theValue[0];}if( document.getElementById('deviId'+element_id) != undefined){		document.getElementById('deviId'+element_id).value = theValue[1];}if( document.getElementById('devicode'+element_id) != undefined){		document.getElementById('devicode'+element_id).value = theValue[2];}if( document.getElementById('deviname'+element_id) != undefined){		document.getElementById('deviname'+element_id).value = theValue[3];}if( document.getElementById('devi_wkctcode'+element_id) != undefined){		document.getElementById('devi_wkctcode'+element_id).value = theValue[4];}if( document.getElementById('devi_wkctname'+element_id) != undefined){		document.getElementById('devi_wkctname'+element_id).value = theValue[5];}if( document.getElementById('DeptID'+element_id) != undefined){		document.getElementById('DeptID'+element_id).value = theValue[6];}if( document.getElementById('deviMhps'+element_id) != undefined){		document.getElementById('deviMhps'+element_id).value = theValue[7];}	}}
function doCa_itemfee_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&popid=57&recvTablename=&displayName=ca_itemfee'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('fee_id'+element_id) != undefined){		document.getElementById('fee_id'+element_id).value = theValue[0];}if( document.getElementById('fee_name'+element_id) != undefined){		document.getElementById('fee_name'+element_id).value = theValue[1];}	}}
function doBa_routercode_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=router_code&dlgTitle=标准工艺路线&popid=43&recvTablename=&displayName=ba_routercode'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('Line'+element_id) != undefined){		document.getElementById('Line'+element_id).value = theValue[0];}if( document.getElementById('router_code'+element_id) != undefined){		document.getElementById('router_code'+element_id).value = theValue[1];}if( document.getElementById('router_name'+element_id) != undefined){		document.getElementById('router_name'+element_id).value = theValue[2];}	}}
function doSl_salesitem_view_line(formName,element_name, element_id, thisObj){  
	var today 		= new Date(); 
	var cur_time	= today.getTime(); 
	var theUrl 		= '../MainServlet/FSys000.000.001.00?time='+cur_time+'&orderCon=&dlgTitle=&popid=41&recvTablename=&displayName=sl_salesitem_view'; 
	var style			= 'status:no;help:no;dialogWidth:28;dialogHeight:27;dialogTop:100;dialogLeft:250' 
	var theValue 	= window.showModalDialog(theUrl,null,style); 
	if(theValue==null){ 
  theValue=''; 
	} 	if(theValue.length==0 || theValue[0]==undefined){ 	}else{ if( document.getElementById('SItem'+element_id) != undefined){		document.getElementById('SItem'+element_id).value = theValue[0];}if( document.getElementById('Item'+element_id) != undefined){		document.getElementById('Item'+element_id).value = theValue[1];}	}}

 //syscodeClassScript script 
function doAppclasscode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=appclasscode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doPlannercode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=plannercode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doBuyercode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=buyercode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doSalesmancode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=salesmancode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doMakebuycode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=makebuycode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doItemtypecode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=itemtypecode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doStatustypecode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=statustypecode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doOrderpolicycode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=orderpolicycode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doChilditemcode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=childitemcode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doQuantitytypecode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=quantitytypecode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doCurrency(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=currency&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doMrpsrccode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=mrpsrccode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}
function doMachinemodelcode(formName, element_name, thisObj){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=machinemodelcode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]==undefined){}	else{		if(eval('document.'+ formName) !=undefined){			if(eval('document.'+ formName).elements[element_name]!= undefined){					eval('document.'+ formName).elements[element_name].value = theValue[0];			}			if(eval('document.'+ formName).elements[element_name+'_textpop']!= undefined){				eval('document.'+ formName).elements[element_name+'_textpop'].value = theValue[1];			}		}else{ 			thisObj.value = theValue[0]; 		}	}}

 //syscodeClassScript_line script 
function doFolk_line(formName, element_name, element_id, thisObj){var today 		= new Date();var cur_time	= today.getTime();var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=folk&time="+cur_time;var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";var theValue 	= window.showModalDialog(theUrl,null,style);if(theValue==null){ theValue="";	}if(theValue.length==0 || theValue[0]=="undefined"){}else{ if(document.getElementById(element_name+element_id) != undefined){		document.getElementById(element_name+element_id).value = theValue[0]; 		if(document.getElementById(element_name+'_textpop'+element_id)!= undefined){			document.getElementById(element_name+'_textpop'+element_id).value = theValue[1];		}	}else{ 		thisObj.value = theValue[0]; 	}}	}
function doCurrency_line(formName, element_name, element_id, thisObj){var today 		= new Date();var cur_time	= today.getTime();var theUrl 		= "../MainServlet/FIIP000.000.005.02?fileName=texpop_normal.jsp&code_class=currency&time="+cur_time;var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";var theValue 	= window.showModalDialog(theUrl,null,style);if(theValue==null){ theValue="";	}if(theValue.length==0 || theValue[0]=="undefined"){}else{ if(document.getElementById(element_name+element_id) != undefined){		document.getElementById(element_name+element_id).value = theValue[0]; 		if(document.getElementById(element_name+'_textpop'+element_id)!= undefined){			document.getElementById(element_name+'_textpop'+element_id).value = theValue[1];		}	}else{ 		thisObj.value = theValue[0]; 	}}	}

 //syscodeClass_selectScript script 
function doRetirereasoncode(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=retirereasoncode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doNation(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=nation&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doEducation(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=education&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doLeague(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=league&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doMajor(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=major&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doGybumen(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=gybumen&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doGyzhiwei(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=gyzhiwei&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doGypeoplemode(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=gypeoplemode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doElectorate(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=electorate&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doSex(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=sex&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doMarry(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=marry&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doEnterprisecode(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=enterprisecode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doFolk(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=folk&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}
function doCardfeetypecode(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= "../MainServlet/FIIP000.000.005.02?code_class=cardfeetypecode&time="+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue="";	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval("document."+ formName).elements[element_name].value = theValue[0];		if(eval("document."+ formName).elements[element_name+'_textpop']!= undefined){			eval("document."+ formName).elements[element_name+'_textpop'].value = theValue[1];		}	}}

 //popFunction_thisObj script 
function doYesno(formName, element_name, thisObj){var today 		= new Date();var cur_time	= today.getTime();var theUrl 		= "../poppage/yesno.jsp?time="+cur_time;var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";var theValue 	= window.showModalDialog(theUrl,null,style);if(theValue==null){ theValue="";	}if(theValue.length==0 || theValue[0]=="undefined"){}		thisObj.value = theValue[0];	}

 //popFunction_a script 
function doYesno_a(formName, element_name){var today 		= new Date();var cur_time	= today.getTime();var theUrl 		= "../poppage/yesno_a.jsp?time="+cur_time;var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";var theValue 	= window.showModalDialog(theUrl,null,style);if(theValue==null){ theValue="";	}if(theValue.length==0 || theValue[0]=="undefined"){} else if(eval('document.'+ formName) != undefined  && eval('document.'+ formName).elements[element_name] != undefined){		eval('document.'+ formName).elements[element_name].value = theValue[0]; 	}else{ 	}}

 //specifiedCode_selectScript script 
function doSso_department(formName, element_name){	var today 		= new Date();	var cur_time	= today.getTime();	var theUrl 		= '../MainServlet/FIIP000.000.005.12?dbtable=sso_department&field_code=first_dp_id&field_name=first_dp_name&time='+cur_time;	var style			= "status:no;help:no;dialogWidth:25;dialogHeight:23;dialogTop:100;dialogLeft:250";	var theValue 	= window.showModalDialog(theUrl,null,style);	if(theValue==null){ theValue='';	}	if(theValue.length==0 || theValue[0]=="undefined"){}	else{ 		eval('document.'+ formName).elements[field_code].value = theValue[0];		eval('document.'+ formName).elements[field_name].value = theValue[1];	}}
